routes/web.php
<?php

use App\Http\Controllers\TicketController;
use App\Models\Ticket;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('tickets',TicketController::class);
Route::get('reply/{id}',[TicketController::class,'reply']);

Route::get('ticketShow/{id}',[TicketController::class,'ticketShow']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Reply.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    use HasFactory;

    protected $guarded = [];


    public function ticket(){
        return $this->belongsTo(Ticket::class);
    }
}

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ticket extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = [];


    public function reply(){
        return $this->hasOne(Reply::class);
    }



}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ticket;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $tickets = Ticket::where('status', '=', 'Open')->get();

        return view('tickets.index',compact('tickets'));
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Mailers\AppMailer;

use App\Models\Reply;
use App\Models\Ticket;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tickets = Ticket::where('status', '=', 'Open')->get();
        return view('tickets.index', compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('newticket');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, AppMailer $mailer)
    {
        //
        $this->validate($request, [
            'client_name'           => 'required',
            'client_problem'        => 'required',
            'client_email'          => 'required|email',
            'client_phone'          => 'required',
        ]);

        $useremail = $request->input('client_email');

        $ticket = Ticket::create([
            'client_name'          => $request->input('client_name'),
            'client_problem'       => $request->input('client_problem'),
            'client_email'         => $useremail,
            'client_phone'         => $request->input('client_phone'),
            'ticket_number' => Str::random(10),
            'status'        => "Open",
        ]);



        $mailer->sendTicketInformation($useremail, $ticket);

        return redirect()->back()->with("status", "Your Ticket Number is:  $ticket->ticket_number has been opened.");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        //
        return view('tickets.show', compact('ticket'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {
        //
        $ticket->update([
            'status' => 'Closed',
        ]);

        $tickets = Ticket::where('status', '=', 'Open')->get();

        return view('tickets.index',compact('tickets'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ticket $ticket, AppMailer $mailer)
    {
        //

        $request->validate([
            'reply' => 'required',
        ]);

        $useremail = $ticket->client_email;

        $reply = new Reply([
            'reply' => $request->input('reply'),
            'ticket_id' => $ticket->id,
        ]);

        $reply->save();

        $mailer->sendTicketReply($reply, $ticket);

        return redirect()->back()->with("status", "Reply has been sent to client");


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        //

    }

    public function ticketShow($id)
    {

        $ticket = Ticket::where('ticket_number',$id)->first();

        $reply = $ticket->reply;
        return response()->json($ticket);
    }



}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/includes/flash.blade.php
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>

                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/newticket.blade.php
<x-master>
    @section('content')
        <h1 class="h3 mb-2 text-gray-800">Tickets</h1>


        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="float-right">
                    <a href="{{route('tickets.create')}}" class="btn btn-success">Open A New Ticket</a>
                </div>
                <div class="float-right">
                    <a href="{{url('/')}}" class="btn btn-primary">Check Ticket</a>
                </div>
            </div>
            <div class="card-body">
                @include('includes.flash')
                <div class="table-responsive">
                    <form method="POST" action="{{route('tickets.store')}}" enctype="multipart/form-data" id="upload_image_form">
                        @csrf
                        <div class="form-group">
                            <label for="client_name">Name </label>
                            <input type="text" class="form-control" id="client_name" name="client_name">
                        </div>
                        <div class="form-group">
                            <label for="client_email">Email </label>
                            <input type="email" class="form-control" id="client_email" name="client_email">
                        </div>
                        <div class="form-group">
                            <label for="client_phone">Phone</label>
                            <input type="text" class="form-control" id="client_phone" name="client_phone">
                        </div>
                        <div class="form-group">
                            <label for="client_problem">Problem</label>
                            <textarea name="client_problem" id="client_problem" class="form-control" rows="5"></textarea>
                        </div>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>




            <div id="ticket_result">
                <table>
                    <tr>
                        <td id="results"></td>
                    </tr>
                </table>
            </div>
        </div>


    @endsection

    @section('js')

    @endsection




</x-master>

resources/views/tickets/index.blade.php
<x-master>
    @section('content')
        <h1 class="h3 mb-2 text-gray-800">Tickets</h1>


        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Tickets</h6>
            </div>
            <div class="card-body">
                @include('includes.flash')
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Ticket Number</th>
                            <th>Client Name</th>
                            <th>Client Email</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Ticket Number</th>
                            <th>Client Name</th>
                            <th>Client Email</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @foreach($tickets as $ticket)
                            <tr>
                                <td>{{$ticket->ticket_number}}</td>
                                <td>{{$ticket->client_name}}</td>
                                <td>{{$ticket->client_email}}</td>
                                <td>{{$ticket->status}}</td>
                                <td>
                                    <a href="{{ route('tickets.show', $ticket->id) }}" class="btn btn-success">Show

                                    </a>
                                    <a href="{{ route('tickets.edit',$ticket->id)}}" class="btn btn-danger">Close ticket</a>


                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    @endsection

    @section('js')
        <!-- Page level plugins -->
            <script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
            <script src="{{asset('vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

            <!-- Page level custom scripts -->
            <script src="{{asset('js/demo/datatables-demo.js')}}"></script>
        @endsection
</x-master>

resources/views/tickets/show.blade.php
<x-master>
    @section('content')
        <h1 class="h3 mb-2 text-gray-800">Ticket</h1>


        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h4 class="m-0 font-weight-bold text-primary"><h3>{{$ticket->ticket_number}}</h3></h4>
            </div>
            <div class="card-body">
                @include('includes.flash')
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th scope="row">Client name</th>
                            <td>{{$ticket->client_name}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Client Email</th>
                            <td>{{$ticket->client_email}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Client Phone</th>
                            <td>{{$ticket->client_phone}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Client Problem</th>
                            <td>{{$ticket->client_problem}}</td>
                        </tr>
                        <tr>
                            <th scope="row"></th>
                            <td><h4>Replies to Client</h4></td>
                        </tr>

                        @foreach($ticket->reply as $reply)
                            <tr>
                                <th></th>
                                <td>{{$reply->reply}}</td>
                            </tr>
                            @endforeach



                        <tr>

                            <th>Reply</th>
                            <td>
                                <form method="post" action="{{ route('tickets.update', $ticket->id) }}">
                                    @method('PATCH')
                                    @csrf
                                    <div class="form-group">
                                        <textarea name="reply" id="reply" class="form-control" rows="10"></textarea>
                                    </div>
                                    <button type="submit" class="btn btn-success">Reply</button>
                                    <a href="{{ route('tickets.edit',$ticket->id)}}" class="btn btn-danger">Close ticket</a>
                                </form>

                            </td>

                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <div class="card shadow mb-4">


        </div>


    @endsection

    @section('js')

    @endsection
</x-master>